# Generated by Django 3.1.5 on 2021-02-24 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='id',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menu',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='menus.menu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='type',
            field=models.CharField(choices=[('item', 'Item'), ('category', 'Category')], default='item', max_length=10, primary_key='MenuItem', serialize=False),
        ),
        migrations.DeleteModel(
            name='MenuCategory',
        ),
    ]
