# Generated by Django 3.1.5 on 2021-02-24 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_auto_20210224_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menus.menuitem'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='type',
            field=models.CharField(choices=[('item', 'Item'), ('category', 'Category')], default='item', max_length=10, primary_key='MenuItem', serialize=False),
        ),
    ]
