# Generated by Django 3.1.5 on 2021-02-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0008_auto_20210224_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='type',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
