# Generated by Django 3.1.5 on 2021-03-07 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0010_menuitem_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='child',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='child',
            field=models.ManyToManyField(blank=True, to='menus.MenuItem'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menus.menu'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='type',
            field=models.CharField(choices=[('item', 'Item'), ('category', 'Category')], default='item', max_length=10),
        ),
    ]
