# Generated by Django 3.1.5 on 2021-03-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0012_auto_20210307_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='child',
            new_name='parent',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='type',
            field=models.CharField(choices=[('item', 'Item'), ('category', 'Category')], default='item', max_length=10),
        ),
    ]
